[cerebrium.deployment]
name = "3-asgi-graceful-shutdown"
include = ["./*"]
exclude = [".*"]

[cerebrium.hardware]
cpu = 1
memory = 1.0
compute = "CPU"
gpu_count = 0
provider = "aws"
region = "us-east-1"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 2
cooldown = 30
replica_concurrency = 1

[cerebrium.runtime.custom]
port = 8000
dockerfile_path = "./Dockerfile"