[cerebrium.deployment]
name = "18-chatterbox-tts"
python_version = "3.11"
docker_base_image_url = "debian:bookworm-slim"
disable_auth = true
include = ['./*', 'main.py', 'cerebrium.toml']
exclude = ['.*']

[cerebrium.hardware]
cpu = 4.0
memory = 12.0
compute = "AMPERE_A10"
region = "us-east-1"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 2
cooldown = 500
replica_concurrency = 10
scaling_metric = "concurrency_utilization"

[cerebrium.dependencies.pip]
"chatterbox-tts" = "latest"
"fastapi[standard]" = "latest"

[cerebrium.runtime.custom]
port = 5000
entrypoint = ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
